let productData = [
  
  {
    id:'001',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-12/paan-corner_web.png',
  },
  {
    id:'002',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-2_10.png',
  },
  {
    id:'003',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-3_9.png',
  },
  {
    id:'004',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-4_9.png',
  },
  {
    id:'005',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-5_4.png',
  },
  {
    id:'006',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-6_5.png',
  },
  {
    id:'007',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-7_3.png',
  },
  {
    id:'008',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-8_4.png',
  },
  {
    id:'009',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-9_3.png',
  },
  {
    id:'010',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-10.png',
  },
  {
    id:'011',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-11.png',
  },
  {
    id:'012',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-12.png',
  },
  {
    id:'013',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-13.png',
  },
  {
    id:'014',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-14.png',
  },
  {
    id:'015',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-15.png',
  },
  {
    id:'016',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-16.png',
  },
  {
    id:'017',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-17.png',
  },
  {
    id:'018',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-18.png',
  },
  {
    id:'019',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-19.png',
  },
  {
    id:'020',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-20.png',
  },
];
let dairyProducts = [
  {
    id:'001',
    item_name:'Milky Mist Paneer',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/32908a.jpg?ts=1687948399',
    weight:'500 g',
    price:'290',
    origanal_price:'310',
    quentity:'1',
  },
  {
    id:'002',
    item_name:'Britannia Whole..',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/127031a.jpg?ts=1688811024',
    weight:'400 g',
    price:'55',
    origanal_price:'64',
    quentity:'1',
  },
  {
    id:'003',
    item_name:'Amul Salted Butter',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/160a.jpg?ts=1689327537',
    weight:'500 g',
    price:'285',
    origanal_price:'300',
    quentity:'1',
  },
  {
    id:'004',
    item_name:'Amul Pure Milk..',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/168a.jpg?ts=1689327537',
    weight:'200 g',
    price:'144',
    origanal_price:'160',
    quentity:'1',
  },
  {
    id:'005',
    item_name:'Amul Mithai Mate..',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/26164a.jpg?ts=1690814323',
    weight:'200 g',
    price:'66',
    origanal_price:'70',
    quentity:'1',
  },
  {
    id:'006',
    item_name:'Nandini Curd',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/259923a.jpg?ts=1690813648',
    weight:'500 g',
    price:'25',
    origanal_price:'27',
    quentity:'1',
  },
  {
    id:'007',
    item_name:'Nandini Toned..',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=120,h=120/app/images/products/full_screen/pro_37083.jpg?ts=1700652993',
    weight:'500 g',
    price:'24',
    origanal_price:'26',
    quentity:'1',
  },
  {
    id:'008',
    item_name:'Britannia Milk Bread',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/480950a.jpg?ts=1687523763',
    weight:'400 g',
    price:'50',
    origanal_price:'60',
    quentity:'1',
  },
  {
    id:'009',
    item_name:'Nestle Milkmaid..',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/10491a.jpg?ts=1688463545',
    weight:'360 g',
    price:'143',
    origanal_price:'144',
    quentity:'1',
  },
  {
    id:'010',
    item_name:'Amul Cheese Cubes',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/170a.jpg?ts=1704366792',
    weight:'200 g',
    price:'134',
    origanal_price:'140',
    quentity:'1',
  },
  {
    id:'011',
    item_name:'Britannia Brown..',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/15364a.jpg?ts=1687525088',
    weight:'400 g',
    price:'55',
    origanal_price:'60',
    quentity:'1',
  },
  {
    id:'012',
    item_name:'Nandini Paneer',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/37076a.jpg?ts=1690814319',
    weight:'200 g',
    price:'100',
    origanal_price:'110',
    quentity:'1',
  },
  {
    id:'013',
    item_name:'Amul Blend Diced..',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/439697a.jpg?ts=1688471557',
    weight:'200 g',
    price:'125',
    origanal_price:'135',
    quentity:'1',
  },
  {
    id:'014',
    item_name:'Ranch Ice Cream',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/486522a.jpg?ts=1688629983',
    weight:'500 g',
    price:'300',
    origanal_price:'350',
    quentity:'1',
  },
  {
    id:'015',
    item_name:'Shreyas Milk',
    img_src:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoemoYLvRJ91sUS8PogjsFINXoDbouLbzd-Q&usqp=CAU',
    weight:'500 g',
    price:'300',
    origanal_price:'350',
    quentity:'1',
  },

];
let snacksProducts =[
  {
    id:'001',
    item_name:'Sorrentina Honestly Italian Black Truffle Chips',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/539700a.jpg',
    weight:'45 g',
    price:'99',
    origanal_price:'100',
  },
  {
    id:'002',
    item_name:'Jolochip Last Chip Challenge Chips',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/521719a.jpg',
    weight:'5 g',
    price:'249',
    origanal_price:'255',
  },
  {
    id:'003',
    item_name:'The Healthy Binge Moringa Jowar Chips',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/506474a.jpg?ts=1691572719',
    weight:'4*40 g',
    price:'144',
    origanal_price:'150',
  },
  {
    id:'004',
    item_name:'A1 Chips Banana Jaggery Chips',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/499832a.jpg?ts=1687339837',
    weight:'250 g',
    price:'140',
    origanal_price:'155',
  },
  {
    id:'005',
    item_name:'The Healthy Binge Smokey BBQ Quinoa Chips',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/506439a.jpg?ts=1691572719',
    weight:'4*40 g',
    price:'144',
    origanal_price:'150',
  },
  {
    id:'006',
    item_name:'DOKi Kerala Fry Buffalo Jerky',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/500337a.jpg?ts=1685708716',
    weight:'30 g',
    price:'199',
    origanal_price:'210',
  },
  {
    id:'007',
    item_name:'DOKi Buffalo Jerky (Tellicherry Pepper Flavour)',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/500987a.jpg',
    weight:'30 g',
    price:'199',
    origanal_price:'210',
  },
  {
    id:'008',
    item_name:'DOKi Chicken Jerky (Korean Gochujang Flavour)',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/500986a.jpg',
    weight:'30 g',
    price:'199',
    origanal_price:'210',
  },
  {
    id:'009',
    item_name:'DOKi Korean Gochujang Buffalo Jerky',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/500334a.jpg?ts=1685708716',
    weight:'30 g',
    price:'199',
    origanal_price:'210',
  },
  {
    id:'010',
    item_name:'DOKi Smoky Masala Chicken Chips',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/500332a.jpg?ts=1685708716',
    weight:'30 g',
    price:'199',
    origanal_price:'210',
  },

];
let PetCare =[
  {
    id:'001',
    item_name:'Kennel Kitchen Chicken Chunks in Gravy Dog Food (Adult & Puppy)',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/462433a.jpg?ts=1697279745',
    weight:'70 g',
    price:'49',
    origanal_price:'50',
  },
  {
    id:'002',
    item_name:'Kennel Kitchen Soft Baked Lamb With Pumpkin Sticks Dog Treat',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/491824a.jpg?ts=1687501901',
    weight:'70 g',
    price:'180',
    origanal_price:'199',
  },
  {
    id:'003',
    item_name:'Glenand Dog Biscuit',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/496043a.jpg?ts=1687338947',
    weight:'3 kg',
    price:'1080',
    origanal_price:'1100',
  },
  {
    id:'004',
    item_name:'Royal Canin Dog Food (Maxi Adult)',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/12471a.jpg?ts=1687525088',
    weight:'4 kg',
    price:'3350',
    origanal_price:'3360',
  },
  {
    id:'005',
    item_name:'Royal Canin Dry Dog Food (Mini Puppy)',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/12473a.jpg?ts=1686222813',
    weight:'4 kg',
    price:'4050',
    origanal_price:'4055',
  },
  {
    id:'006',
    item_name:'Mutt of Course Fish Jerky Cat & Dog Treat',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/506239a.jpg',
    weight:'85 g',
    price:'499',
    origanal_price:'500',
  },
  {
    id:'007',
    item_name:'Mutt of Course Scooby Snacks Dog Treat (Chicken & Strawberry)',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/537307a.jpg?ts=1699862661',
    weight:'70 g',
    price:'299',
    origanal_price:'300',
  },
  {
    id:'008',
    item_name:'Mutt of Course Cheese Cracker Dog Treat',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/506238a.jpg?ts=1690829631',
    weight:'100 g',
    price:'300',
    origanal_price:'400',
  },
  {
    id:'009',
    item_name:'Mutt of Course Fish Jerky Cat & Dog Treat',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/506239a.jpg',
    weight:'85 g',
    price:'',
    origanal_price:'',
  },
  {
    id:'010',
    item_name:'Sploot Meaty Mutton Dog Food',
    img_src:'https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=120,h=120/app/images/products/full_screen/pro_507869.jpg?ts=1704884228',
    weight:'200 g',
    price:'250',
    origanal_price:'300',
  },
];
let coldDrinksproducts = [
  {
    id:'001',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'002',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'003',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'004',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'005',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'006',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'007',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'008',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'009',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'010',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
];
let candieProducts = [
  {
    id:'001',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'002',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'003',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'004',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'005',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'006',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'007',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'008',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'009',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
  {
    id:'010',
    item_name:'',
    img_src:'',
    weight:'',
    price:'',
    origanal_price:'',
  },
];